---
title: KrigR Workshop - Introduction to the R Package
author: Erik Kusch
date: '2021-01-28'
slug: krigrworkshop
categories:
 - Workshop
 - KrigR
tags:
 - Climate Data
 - Statistical Downscaling
 - KrigR
subtitle: 'Climate Data for your Study Needs'
summary: 'A short introduction to the KrigR R Package designed to download, aggregate, and statistically downscale state-of-the-art climate data.'
authors: []
lastmod: '2021-01-28T18:00:00+01:00'
featured: no
image:
 caption: ''
 focal_point: ''
 preview_only: no
projects: [KrigR]
output:
 blogdown::html_page:
   toc: true
   toc_depth: 2
   number_sections: false
---


<div id="TOC">
<ul>
<li><a href="#recording-availability">Recording Availability</a></li>
<li><a href="#setting-things-up">Setting Things Up</a><ul>
<li><a href="#installing-krigr">Installing <code>KrigR</code></a></li>
<li><a href="#setting-up-directories">Setting Up Directories</a></li>
<li><a href="#downloading-shapefiles">Downloading Shapefiles</a></li>
<li><a href="#plotting-functions">Plotting Functions</a></li>
</ul></li>
<li><a href="#kriging---the-three-steps">Kriging - The Three Steps</a><ul>
<li><a href="#climate-data">Climate Data</a></li>
<li><a href="#covariates-1">Covariates</a></li>
<li><a href="#kriging">Kriging</a></li>
</ul></li>
<li><a href="#kriging---the-pipeline">Kriging - The Pipeline</a></li>
<li><a href="#getting-more-out-of-krigr">Getting More out of <code>KrigR</code></a><ul>
<li><a href="#kriging-by-shapefile">Kriging By Shapefile</a></li>
<li><a href="#kriging-for-point-data">Kriging For Point-Data</a></li>
<li><a href="#multi-core-kriging">Multi-Core Kriging</a></li>
<li><a href="#weighted-local-kriging">Weighted Local Kriging</a></li>
<li><a href="#aggregation-of-temporal-resolutions">Aggregation of Temporal Resolutions</a></li>
<li><a href="#kriging-to-match-already-available-data">Kriging to Match Already Available Data</a></li>
<li><a href="#the-call-list">The Call List</a></li>
</ul></li>
<li><a href="#using-third-party-data">Using Third-Party Data</a><ul>
<li><a href="#climate-data-3">Climate Data</a></li>
<li><a href="#covariates-4">Covariates</a></li>
<li><a href="#kriging-3">Kriging</a></li>
</ul></li>
<li><a href="#session-info">Session Info</a></li>
</ul>
</div>

<style>

#content {
    max-width: 3200px !important;
}

p.atten {
color: #ffffff;
background-color: #a30000;
padding: 15px;
border: 1px;
border-radius: 5px;
}

p.lookhere {
color: #ffffff;
background-color: #073b26;
padding: 15px;
border: 1px;
border-radius: 5px;
}
</style>
<div id="recording-availability" class="section level1">
<h1>Recording Availability</h1>
<p>A recording of me presenting much of the contents herein can be found on <a href="https://www.youtube.com/watch?v=wwb107L4wVw&amp;ab_channel=ErikKusch">YouTube</a>.</p>
</div>
<div id="setting-things-up" class="section level1">
<h1>Setting Things Up</h1>
<div id="installing-krigr" class="section level2">
<h2>Installing <code>KrigR</code></h2>
<p>First of all, we need to install <code>KrigR</code>. Since we are currently preparing the package for submission to CRAN, it is only available through the associated GitHub repository (<a href="https://github.com/ErikKusch/KrigR" class="uri">https://github.com/ErikKusch/KrigR</a>) for the time being. There, you may also find presentations as well as this guide/workshop.</p>
<p>Here, we use the <code>devtools</code> package within <code>R</code> to get access to the <code>install_github()</code> function. For this to run, we need to tell <code>R</code> to not stop the installation from GitHub as soon as a warning is produced. This would stop the installation process as early as one of the <code>KrigR</code> dependencies hits a warning as benign as “Package XYZ was built under R Version X.X.X” which can usually be ignored safely.</p>
<pre class="r"><code>Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = &quot;true&quot;)
devtools::install_github(&quot;https://github.com/ErikKusch/KrigR&quot;)
library(KrigR)</code></pre>
<p>For the sake of this tutorial, we need some extra packages for visualisations. We check if they are already installed, subsequently install (if necessary) and load them with this user-defined function:</p>
<pre class="r"><code>install.load.package &lt;- function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, repos = &quot;http://cran.us.r-project.org&quot;)
  }
  require(x, character.only = TRUE)
}
package_vec &lt;- c(
  &quot;tidyr&quot;, # for turning rasters into ggplot-dataframes
  &quot;ggplot2&quot;, # for plotting
  &quot;viridis&quot;, # colour palettes
  &quot;cowplot&quot;, # gridding multiple plots
  &quot;rosm&quot;, # obtaining satellite maps
  &quot;gimms&quot; # to get some pre-existing data to match in our downscaling
)
sapply(package_vec, install.load.package)</code></pre>
<pre><code>##   tidyr ggplot2 viridis cowplot    rosm   gimms 
##    TRUE    TRUE    TRUE    TRUE    TRUE    TRUE</code></pre>
<p>Before we can proceed, you need to open up an account at the CDS and create an API key by following this link: <a href="https://cds.climate.copernicus.eu/api-how-to" class="uri">https://cds.climate.copernicus.eu/api-how-to</a>. This is required so that you may issue download requests through the <code>KrigR</code> package. Once you have done so, please register the user ID and API Key as characters as seen below:</p>
<pre class="r"><code>API_User &lt;- &quot;XXXXXX&quot;
API_Key &lt;- &quot;XXXXXXX&quot;</code></pre>
</div>
<div id="setting-up-directories" class="section level2">
<h2>Setting Up Directories</h2>
<p>The tutorial is designed to run completely from scratch. For this to work in a structured way, we create a folder/directory structure so that we got some nice compartments on our hard drives for where each separate Kriging process is run. We create the following directories:<br />
- A <strong>data</strong> directory for all of our individual Kriging processes<br />
- A <strong>shapefile</strong> directory (located within our data directory) for all of the shapefiles that we will use</p>
<pre class="r"><code>Dir.Base &lt;- getwd() # identifying the current directory
Dir.Data &lt;- file.path(Dir.Base, &quot;Data&quot;) # folder path for data
Dir.Shapes &lt;- file.path(Dir.Data, &quot;Shapes&quot;) # folder path for shapefiles
Dirs &lt;- sapply(c(Dir.Data, Dir.Shapes), function(x) if (!dir.exists(x)) dir.create(x))</code></pre>
</div>
<div id="downloading-shapefiles" class="section level2">
<h2>Downloading Shapefiles</h2>
<p>Here, we download some of the most commonly used shapefiles (for our analyses using <code>KrigR</code> so far, at least). For repeat code-sourcing, we have implemented checks which only trigger the download of a given shapefile set if the data in question is not present in our <em>Shapes</em> directory yet.</p>
<p class="lookhere">
This tutorial doesn’t make use of all the shapefiles we download here. We simply thought it prudent to show you what we have found to be useful and how to get your hands on the data in a reproducible way.
</p>
<div id="land-cover" class="section level3">
<h3>Land Cover</h3>
<p>As we will see in this tutorial, masking out unnecessary areas from our analyses speeds up Kriging tremendously. Often, this will entail limiting data sets to terrestrial habitats. This land mask here does a terrific job at masking out non-land areas.</p>
<pre class="r"><code>#### LAND MASK (for masking covariates according to land vs. sea)
if (!file.exists(file.path(Dir.Shapes, &quot;LandMask.zip&quot;))) { # if not downloaded yet
  download.file(&quot;https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_land.zip&quot;,
    destfile = file.path(Dir.Shapes, &quot;LandMask.zip&quot;)
  ) # download cultural vector
  unzip(file.path(Dir.Shapes, &quot;LandMask.zip&quot;), exdir = Dir.Shapes) # unzip data
}
LandMask &lt;- readOGR(Dir.Shapes, &quot;ne_10m_land&quot;, verbose = FALSE) # read
ggplot() +
  geom_polygon(data = LandMask, aes(x = long, y = lat, group = group), colour = &quot;darkred&quot;, fill = &quot;black&quot;) +
  theme_bw() +
  labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/LandMask-1.png" width="1440" /></p>
</div>
<div id="states-provinces" class="section level3">
<h3>States &amp; Provinces</h3>
<p>Political divisions are often what policy makers are after. Hence, we also download a shapefile for states and provinces across the Globe.</p>
<pre class="r"><code>#### STATE MASK (for within-nation borders)
if (!file.exists(file.path(Dir.Shapes, &quot;StateMask.zip&quot;))) { # if not downloaded yet
  download.file(&quot;https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces.zip&quot;,
    destfile = file.path(Dir.Shapes, &quot;StateMask.zip&quot;)
  ) # download cultural vector
  unzip(file.path(Dir.Shapes, &quot;StateMask.zip&quot;), exdir = Dir.Shapes) # unzip data
}
StateMask &lt;- readOGR(Dir.Shapes, &quot;ne_10m_admin_1_states_provinces&quot;, verbose = FALSE) # read
ggplot() +
  geom_polygon(data = StateMask, aes(x = long, y = lat, group = group), colour = &quot;darkred&quot;, fill = &quot;black&quot;) +
  theme_bw() +
  labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/StateMask-1.png" width="1440" /></p>
<p>As you can see, this shapefile provides a set of rather small (geographically speaking) regions. We will use these for showing how Kriging works within this tutorial because Kriging runs in a timely manner for these regions.</p>
<p>Additionally, it is worth pointing out that www.naturalearthdata.com offers a large host of further shapefile data sets including (but not limited to):<br />
- National borders<br />
- Rivers and Lakes<br />
- Urban areas<br />
- Reefs and Bathymetry</p>
<p>We strongly recommend looking there early on in your projects for any shapefile needs you may have.</p>
</div>
<div id="ecoregions" class="section level3">
<h3>Ecoregions</h3>
<p>When we’re not bound by political boundaries, ecoregions can often help to limit the spatial scope of our macroecological studies to manageable sizes (as far as Kriging effort is concerned).</p>
<pre class="r"><code>#### ECOREGIONS (for ecoregional borders)
if (!file.exists(file.path(Dir.Shapes, &quot;WWF_ecoregions&quot;))) { # if not downloaded yet
  download.file(&quot;http://assets.worldwildlife.org/publications/15/files/original/official_teow.zip&quot;,
    destfile = file.path(Dir.Shapes, &quot;wwf_ecoregions.zip&quot;)
  ) # download regions
  unzip(file.path(Dir.Shapes, &quot;wwf_ecoregions.zip&quot;), exdir = file.path(Dir.Shapes, &quot;WWF_ecoregions&quot;)) # unzip data
}
EcoregionMask &lt;- readOGR(file.path(Dir.Shapes, &quot;WWF_ecoregions&quot;, &quot;official&quot;, &quot;wwf_terr_ecos.shp&quot;), verbose = FALSE) # read
ggplot() +
  geom_polygon(data = EcoregionMask, aes(x = long, y = lat, group = group), colour = &quot;darkred&quot;, fill = &quot;black&quot;) +
  theme_bw() +
  labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/EcoregionMask-1.png" width="1440" /></p>
<p>This particular data set offers the shapes of biomes and biogeographical realms across the Earth. As far as Kriging with the <code>KrigR</code> package is concerned, we heavily <strong>advise against</strong> Kriging using <strong>biogeographical realms</strong> without further consideration since these large regions lead to extreme processing requirements.</p>
</div>
</div>
<div id="plotting-functions" class="section level2">
<h2>Plotting Functions</h2>
<p>In order to easily visualise our Kriging procedure including (1) inputs, (2) covariates, and (3) outputs without repeating too much of the same code, we create a few plotting functions of our own here.</p>
<p class="lookhere">
Don’t worry about understanding how these work off the bat here. Kriging and the package <code>KrigR</code> are what we want to demonstrate here - not visualisation strategies.
</p>
<div id="raw-data" class="section level3">
<h3>Raw Data</h3>
<p>This function plots the raw data that we will krig and exports a single plot of all layers of the input raster:</p>
<pre class="r"><code>Plot_Raw &lt;- function(Raw, Shp = NULL, Dates, Legend = &quot;Air Temperature [K]&quot;) {
  Raw_df &lt;- as.data.frame(Raw, xy = TRUE) # turn raster into dataframe
  colnames(Raw_df)[c(-1, -2)] &lt;- Dates # set colnames
  Raw_df &lt;- gather(data = Raw_df, key = Values, value = &quot;value&quot;, colnames(Raw_df)[c(-1, -2)]) #  make ggplot-ready
  Raw_plot &lt;- ggplot() + # create a plot
    geom_raster(data = Raw_df, aes(x = x, y = y, fill = value)) + # plot the raw data
    facet_wrap(~Values) + # split raster layers up
    theme_bw() +
    labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;) + # make plot more readable
    scale_fill_gradientn(name = Legend, colours = inferno(100)) # add colour and legend
  if (!is.null(Shp)) { # if a shape has been designated
    Raw_plot &lt;- Raw_plot + geom_polygon(data = Shp, aes(x = long, y = lat, group = group), colour = &quot;black&quot;, fill = &quot;NA&quot;) # add shape
  }
  return(Raw_plot)
} # export the plot</code></pre>
</div>
<div id="covariates" class="section level3">
<h3>Covariates</h3>
<p>This function plots the covariate data we will be using by showing each variable on both resolution levels side-by-side:</p>
<pre class="r"><code>Plot_Covs &lt;- function(Covs, Shp = NULL) {
  Plots_ls &lt;- as.list(rep(NA, nlayers(Covs[[1]]) * 2)) # create as many plots as there are covariates variables * 2
  Counter &lt;- 1 # counter for list position
  for (Variable in 1:nlayers(Covs[[1]])) { # loop over all covariate variables
    Covs_Iter &lt;- list(Covs[[1]][[Variable]], Covs[[2]][[Variable]]) # extract the data for this variable
    for (Plot in 1:2) { # loop over both resolutions for the current variable
      Cov_df &lt;- as.data.frame(Covs_Iter[[Plot]], xy = TRUE) # turn raster into data frame
      colnames(Cov_df)[3] &lt;- &quot;Values&quot; # assign a column name to the data column
      Plots_ls[[Counter]] &lt;- ggplot() + # create plot
        geom_raster(data = Cov_df, aes(x = x, y = y, fill = Values)) + # plot the covariate data
        theme_bw() +
        labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;) + # make plot more readable
        scale_fill_gradientn(name = names(Covs_Iter[[Plot]]), colours = cividis(100)) + # add colour and legend
        theme(plot.margin = unit(c(0, 0, 0, 0), &quot;cm&quot;)) # reduce margins (for fusing of plots)
      if (!is.null(Shp)) { # if a shape has been designated
        Plots_ls[[Counter]] &lt;- Plots_ls[[Counter]] + geom_polygon(data = Shp, aes(x = long, y = lat, group = group), colour = &quot;black&quot;, fill = &quot;NA&quot;) # add shape
      }
      Counter &lt;- Counter + 1 # raise list counter
    } # end of resolution loop
  } # end of variable loop
  ggPlot &lt;- plot_grid(plotlist = Plots_ls, ncol = 2, labels = &quot;AUTO&quot;) # fuse the plots into one big plot
  return(ggPlot)
} # export the plot</code></pre>
</div>
<div id="kriged-products" class="section level3">
<h3>Kriged Products</h3>
<p>This function plots the Kriging outputs by splitting them up according to whether they are Kriging predictions or the uncertainties associated with them:</p>
<pre class="r"><code>Plot_Krigs &lt;- function(Krigs, Shp = NULL, Dates, Legend = &quot;Air Temperature [K]&quot;) {
  Type_vec &lt;- c(&quot;Prediction&quot;, &quot;Standard Error&quot;) # these are the output types of krigR
  Colours_ls &lt;- list(inferno(100), rev(viridis(100))) # we want separate colours for the types
  Plots_ls &lt;- as.list(NA, NA) # this list will be filled with the output plots
  for (Plot in 1:2) { # loop over both output types
    Krig_df &lt;- as.data.frame(Krigs[[Plot]], xy = TRUE) # turn raster into dataframe
    colnames(Krig_df)[c(-1, -2)] &lt;- paste(Type_vec[Plot], Dates) # set colnames
    Krig_df &lt;- gather(data = Krig_df, key = Values, value = &quot;value&quot;, colnames(Krig_df)[c(-1, -2)]) # make ggplot-ready
    Plots_ls[[Plot]] &lt;- ggplot() + # create plot
      geom_raster(data = Krig_df, aes(x = x, y = y, fill = value)) + # plot the kriged data
      facet_wrap(~Values) + # split raster layers up
      theme_bw() +
      labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;) + # make plot more readable
      scale_fill_gradientn(name = Legend, colours = Colours_ls[[Plot]]) + # add colour and legend
      theme(plot.margin = unit(c(0, 0, 0, 0), &quot;cm&quot;)) # reduce margins (for fusing of plots)
    if (!is.null(Shp)) { # if a shape has been designated
      Plots_ls[[Plot]] &lt;- Plots_ls[[Plot]] + geom_polygon(data = Shp, aes(x = long, y = lat, group = group), colour = &quot;black&quot;, fill = &quot;NA&quot;) # add shape
    }
  } # end of type-loop
  ggPlot &lt;- plot_grid(plotlist = Plots_ls, ncol = 1, labels = &quot;AUTO&quot;) # fuse the plots into one big plot
  return(ggPlot)
} # export the plot</code></pre>
</div>
</div>
</div>
<div id="kriging---the-three-steps" class="section level1">
<h1>Kriging - The Three Steps</h1>
<p>Using <code>KrigR</code> in this way has us use the functions <code>download_ERA()</code>, <code>download_DEM()</code>, and <code>krigR()</code>. Running these functions by themselves as opposed to executing the <code>KrigR</code> <strong>pipeline</strong> (which we cover later in this tutorial) gives you the most control and oversight of the <code>KrigR</code> workflow.</p>
<p class="lookhere">
We will start with a <strong>simple Kriging process</strong> and subsequently <strong>make it more sophisticated</strong> during this tutorial.
</p>
<p>The most simple way in which you can run the functions of the <code>KrigR</code> package is by specifying a rectangular bounding box (i.e. an <strong>extent</strong>) to specify your study region(s). Here, we will run a small downscaling exercise of my birth-state of Saxony. It is a medium-sized state in the east of Germany and lends itself to some nice statistical downscaling since it presents us with mountainous regions along the south-eastern border and flatland areas towards the north-western edges.</p>
<p>Here’s the full area we will be obtaining and downscaling data for:</p>
<pre class="r"><code>Extent &lt;- extent(c(11.8, 15.1, 50.1, 51.7)) # roughly the extent of Saxony
bmaps.plot(bbox = Extent, type = &quot;AerialWithLabels&quot;, quiet = TRUE, progress = &quot;none&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/StateExt-1.png" width="1440" /></p>
<p>Here, you can see a map of the region with the mountains of the Erzgebirge along the southern border to the Czech Republic as well as the flat terrains around Leipzig in the north of Saxony.</p>
<p>Now, let’s create a separate directory within which we will store the raw ERA5-land data, GMTED2010 DEM covariate data, and Kriging outputs:</p>
<pre class="r"><code>Dir.StateExt &lt;- file.path(Dir.Data, &quot;State_Extent&quot;)
dir.create(Dir.StateExt)</code></pre>
<div id="climate-data" class="section level2">
<h2>Climate Data</h2>
<p>No we are ready to carry out our first download of climate reanalysis data through the <code>KrigR</code> package!</p>
<p>For this part of the tutorial, we download air temperature for a three-day interval around my birthday (03-01-1995) using the extent of my home-state of Saxony.</p>
<p class="atten">
Notice that the downloading of ERA-family reanalysis data may take a short while to start as the download request gets queued with the CDS of the ECMWF before it is executed.
</p>
<pre class="r"><code>State_Raw &lt;- download_ERA(
  Variable = &quot;2m_temperature&quot;,
  DataSet = &quot;era5-land&quot;,
  DateStart = &quot;1995-01-02&quot;,
  DateStop = &quot;1995-01-04&quot;,
  TResolution = &quot;day&quot;,
  TStep = 1,
  Extent = Extent,
  Dir = Dir.StateExt,
  API_User = API_User,
  API_Key = API_Key
)
Plot_Raw(State_Raw, Dates = c(&quot;02-01-1995&quot;, &quot;03-01-1995&quot;, &quot;04-01-1995&quot;))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/ClimExt-1.png" width="1440" /></p>
<p>Now, let’s look at the raster that was produced:</p>
<pre class="r"><code>State_Raw</code></pre>
<pre><code>## class      : RasterBrick 
## dimensions : 19, 36, 684, 3  (nrow, ncol, ncell, nlayers)
## resolution : 0.1, 0.09999996  (x, y)
## extent     : 11.65, 15.25, 49.95, 51.85  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      :  index_1,  index_2,  index_3 
## min values : 267.8741, 266.8182, 262.5400 
## max values : 273.2644, 272.0682, 269.5377</code></pre>
<p>As you can see, we obtained a RasterBrick object with 3 layers of data (one for each day we are interested in). Notice that extent of our downloaded data set does not fit the extent we set earlier manually. This is a precaution we have taken within <code>KrigR</code> to make sure that all data cells you are interested in are covered.</p>
<p class="atten">
<code>KrigR</code> widens the spatial extent that is specified to ensure full coverage of the respective ERA5(-Land) raster cells. Global downloads are not affected by this and work just as you’d expect.
</p>
<p>Additionally, as could be gleamed from the plots above, it is apparent that my home-state got a lot cooler on the day after my birth (04/01/1995) when compared to the two preceding days. What to make of this, I leave up to you because I don’t think I like the interpretation myself if we were to assume causality here.</p>
<p>Keep in mind that every function within the <code>KrigR</code> package produces NetCDF (.nc) files in the specified directory (<code>Dir</code> argument in the function call) to allow for further manipulation outside of <code>R</code> if necessary (for example, using Panoply).</p>
</div>
<div id="covariates-1" class="section level2">
<h2>Covariates</h2>
<p>Next, we use the <code>download_DEM()</code> function which comes with <code>KrigR</code> to obtain elevation data as our covariate of choice. This produces two rasters:</p>
<ol style="list-style-type: decimal">
<li>A raster of <strong>training</strong> resolution which matches the input data in all attributes except for the data in each cell<br />
</li>
<li>A raster of <strong>target</strong> resolution which matches the input data as closely as possible in all attributes except for the resolution (which is specified by the user) and the data in each cell</li>
</ol>
<p>Both of these products are bundled into a <code>list</code> where the first element corresponds to the <em>training</em> resolution and the second element contains the <em>target</em> resolution covariate data. Here, we specify a target resolution of <code>.02</code>.</p>
<pre class="r"><code>Covs_ls &lt;- download_DEM(
  Train_ras = State_Raw,
  Target_res = .02,
  Dir = Dir.StateExt,
  Keep_Temporary = TRUE
)
Plot_Covs(Covs_ls)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/CovExt-1.png" width="1440" /></p>
<p>Alternatively to specifying a target resolution, you can specify a different raster which should be matched in all attributes by the raster at target resolution. We get to this again at a later point in this tutorial.</p>
<p>For now, let’s simply inspect our list of covariate rasters:</p>
<pre class="r"><code>Covs_ls</code></pre>
<pre><code>## [[1]]
## class      : RasterLayer 
## dimensions : 19, 36, 684  (nrow, ncol, ncell)
## resolution : 0.1, 0.09999996  (x, y)
## extent     : 11.65, 15.25, 49.95, 51.85  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : DEM 
## values     : 59.11391, 926.513  (min, max)
## 
## 
## [[2]]
## class      : RasterLayer 
## dimensions : 114, 216, 24624  (nrow, ncol, ncell)
## resolution : 0.01666667, 0.01666667  (x, y)
## extent     : 11.64986, 15.24986, 49.94986, 51.84986  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : DEM 
## values     : 46.5, 1150.25  (min, max)</code></pre>
<p>This set of covariates has 684 and 24624 cells containing values at training and target resolution, respectively.</p>
</div>
<div id="kriging" class="section level2">
<h2>Kriging</h2>
<p>Now let’s krig these data:</p>
<pre class="r"><code>KrigStart &lt;- Sys.time()
State_Krig &lt;- krigR(
  Data = State_Raw, # data we want to krig as a raster object
  Covariates_coarse = Covs_ls[[1]], # training covariate as a raster object
  Covariates_fine = Covs_ls[[2]], # target covariate as a raster object
  Keep_Temporary = FALSE, # we don&#39;t want to retain the individually kriged layers on our hard-drive
  Cores = 1, # we want to krig on just one core
  FileName = &quot;State_Ext.nc&quot;, # the file name for our full kriging output
  Dir = Dir.StateExt # which directory to save our final input in
)
KrigStop &lt;- Sys.time()
Plot_Krigs(State_Krig, Dates = c(&quot;02-01-1995&quot;, &quot;03-01-1995&quot;, &quot;04-01-1995&quot;))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/KrigExt-1.png" width="1440" /></p>
<p>There we go. All the data has been downscaled and we do have uncertainties recorded for all of our outputs. As you can see, the elevation patterns show up clearly in our kriged air temperature output. Furthermore, you can see that our certainty of Kriging predictions drops on the 04/01/1995 in comparison to the two preceding days. However, do keep in mind that a maximum standard error of 0.195, 0.206, 0.333 (for each layer of our output respectively) on a total range of data of 6.553, 6.318, 7.788 (again, for each layer in the output respectively) is evident of a downscaling result we can be confident in.</p>
<p>Now, what does the output actually look like?</p>
<pre class="r"><code>State_Krig[-3] # we will talk later about why we leave out the third list element produced by krigR here</code></pre>
<pre><code>## $Kriging_Output
## class      : RasterBrick 
## dimensions : 114, 216, 24624, 3  (nrow, ncol, ncell, nlayers)
## resolution : 0.01666667, 0.01666667  (x, y)
## extent     : 11.64986, 15.24986, 49.94986, 51.84986  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : var1.pred.1, var1.pred.2, var1.pred.3 
## min values :    266.8146,    265.6941,    261.6227 
## max values :    273.3675,    272.0124,    269.4109 
## 
## 
## $Kriging_SE
## class      : RasterBrick 
## dimensions : 114, 216, 24624, 3  (nrow, ncol, ncell, nlayers)
## resolution : 0.01666667, 0.01666667  (x, y)
## extent     : 11.64986, 15.24986, 49.94986, 51.84986  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : var1.stdev.1, var1.stdev.2, var1.stdev.3 
## min values :    0.1624252,    0.1706871,    0.2581532 
## max values :    0.1951452,    0.2059939,    0.3330932</code></pre>
<p>As output of the <code>krigR()</code> function, we obtain a list of downscaled data as the first element and downscaling standard errors as the second list element.</p>
<p>Finally, let’s see how long it took to carry out this shapefile-informed downscaling:</p>
<pre class="r"><code>BaseTime &lt;- KrigStop - KrigStart
BaseTime</code></pre>
<pre><code>## Time difference of 49.10878 secs</code></pre>
</div>
</div>
<div id="kriging---the-pipeline" class="section level1">
<h1>Kriging - The Pipeline</h1>
<p>Now that we’ve seen how you can execute the <code>KrigR</code> workflow using three separate functions, it is time that we show you the most simplified function call to obtain some downscaled products: the <strong>pipeline</strong>.</p>
<p>First, let’s create a directory which the <code>KrigR</code> pipeline will <em>leak</em> .nc files to. Don’t worry, this leak in the pipeline is very much intentional and of no environmental concern (unless you are running low on disk space).</p>
<pre class="r"><code>Dir.StatePipe &lt;- file.path(Dir.Data, &quot;State_Pipe&quot;)
dir.create(Dir.StatePipe)</code></pre>
<p>We have coded the <code>krigR()</code> function in such a way that it can either be addressed at already present spatial products within your <code>R</code> environment, or handle all the downloading and resampling of input data and covariates for you from scratch. To run the exact same Kriging approach as within our extent-example, we can specify the <code>krigR()</code> function as such:</p>
<pre class="r"><code>Pipe_Krig &lt;- krigR(
  Variable = &quot;2m_temperature&quot;,
  Type = &quot;reanalysis&quot;,
  DataSet = &quot;era5-land&quot;,
  DateStart = &quot;1995-01-02&quot;,
  DateStop = &quot;1995-01-04&quot;,
  TResolution = &quot;day&quot;,
  TStep = 1,
  Extent = Extent,
  API_User = API_User,
  API_Key = API_Key,
  Target_res = .02,
  Cores = 1,
  FileName = &quot;State_Pipe.nc&quot;,
  Dir = Dir.StatePipe,
  Keep_Temporary = FALSE
)
Pipe_Krig[-3] # we will talk later about why we leave out the third list element produced by krigR here
Plot_Krigs(Pipe_Krig, Dates = c(&quot;02-01-1995&quot;, &quot;03-01-1995&quot;, &quot;04-01-1995&quot;))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/PipeExec-1.png" width="1440" /></p>
<p>Let’s just check how this compares to non-pipeline product:</p>
<pre class="r"><code>all.equal(State_Krig[[1]], Pipe_Krig[[1]])</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Surprise! There is no difference.</p>
</div>
<div id="getting-more-out-of-krigr" class="section level1">
<h1>Getting More out of <code>KrigR</code></h1>
<div id="kriging-by-shapefile" class="section level2">
<h2>Kriging By Shapefile</h2>
<p class="lookhere">
The computational cost of Kriging depends on many factors, one of which is number of observation (i.e. raster cells), which we can limit by using a <strong>shapefile</strong>.
</p>
<p>Let’s revisit our above Saxony-Kriging example, but this time, we will use a shapefile to mask for the exact boundaries of the state itself! We extract the shapefile from the states &amp; provinces data set as follows:</p>
<pre class="r"><code>Position &lt;- which(StateMask$name_en == &quot;Saxony&quot;) # find Saxony
State_Shp &lt;- StateMask[Position,]
bmaps.plot(bbox = extent(State_Shp), type = &quot;AerialWithLabels&quot;, quiet = TRUE, progress = &quot;none&quot;, stoponlargerequest = FALSE)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/StateShape-1.png" width="1440" />
Here, you can see a map of the region with. Notice the outline of the state of Saxony; we will reconstruct that using our shapefile.</p>
<p>Again, we create a directory for all the .nc files that our functions create:</p>
<pre class="r"><code>Dir.StateShp &lt;- file.path(Dir.Data, &quot;State_Shape&quot;)
dir.create(Dir.StateShp)</code></pre>
<div id="climate-data-1" class="section level3">
<h3>Climate Data</h3>
<p>Again, we download air temperature data from the ERA5-Land data set for the three days from the second to the fourth of January 1995. This time, however, we limit the data by shapefile.</p>
<pre class="r"><code>State_Raw &lt;- download_ERA(
  Variable = &quot;2m_temperature&quot;,
  DataSet = &quot;era5-land&quot;,
  DateStart = &quot;1995-01-02&quot;,
  DateStop = &quot;1995-01-04&quot;,
  TResolution = &quot;day&quot;,
  TStep = 1,
  Extent = State_Shp,
  Dir = Dir.StateShp,
  API_User = API_User,
  API_Key = API_Key
)
Plot_Raw(State_Raw, Shp = State_Shp, Dates = c(&quot;02-01-1995&quot;, &quot;03-01-1995&quot;, &quot;04-01-1995&quot;))</code></pre>
<img src="{{< blogdown/postref >}}index.en_files/figure-html/ClimShape-1.png" width="1440" />
<p class="lookhere">
Note that we have implemented masking by shapefile in such a way that every cell that is even partially covered by your shapefile is retained in the downloaded ERA5(-Land) data set. Regular masking via the <code>raster</code> package-contained <code>mask()</code> function only retains those cells whose centroids fall within the shapefile boundaries.
</p>
</div>
<div id="covariates-2" class="section level3">
<h3>Covariates</h3>
<p>Again, we obtain elevation data as our covariate of choice:</p>
<pre class="r"><code>Covs_ls &lt;- download_DEM(
  Train_ras = State_Raw,
  Target_res = .02,
  Shape = State_Shp,
  Dir = Dir.StateShp,
  Keep_Temporary = TRUE
)
Plot_Covs(Covs_ls, State_Shp)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/CovShape-1.png" width="1440" />
Notice that despite the covariate rasters (and input rasters, for that matter) containing 578 and 2.080810^{4} for training and target resolution respectively, we only obtain data for 299 and 8765 cells respectively due to our specification of a shapefile.</p>
</div>
<div id="kriging-1" class="section level3">
<h3>Kriging</h3>
<p>Again, we execute our Kriging functionality using the <code>krigR()</code> function:</p>
<pre class="r"><code>KrigStart &lt;- Sys.time() # record when we started
State_Krig &lt;- krigR(
  Data = State_Raw, # what to krig
  Covariates_coarse = Covs_ls[[1]], # covariates at training resolution
  Covariates_fine = Covs_ls[[2]], # covariates at target resolution
  Keep_Temporary = FALSE, # delete temporary krigs of layers
  Cores = 1, # only run this on 1 core
  FileName = &quot;State_Shape.nc&quot;, # save the finished file as this
  Dir = Dir.StateShp # where to save the output
)
KrigStop &lt;- Sys.time() # record when the function was done
Plot_Krigs(State_Krig, Shp = State_Shp, Dates = c(&quot;02-01-1995&quot;, &quot;03-01-1995&quot;, &quot;04-01-1995&quot;))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/KrigShape-1.png" width="1440" /></p>
<p>The results look just like the ones that we obtained without using the shapefile (this time, we only see what’s contained in the shapefile, though). It is noteworthy to highlight the change in uncertainties here. Overall, our uncertainty decreased in going from extent-informed to shapefile-informed kriging in this example. However, we now see some serious chessboard pattern of the uncertainties in our outputs. This is due to the uncertainty decreasing as fine-resolution cells are more closely located towards the centre of a coarse-scaled cell which they have been downscaled from. This behaviour is normal. To obtain more useful kriging standard errors (i.e. uncertainties), we use local Kriging (we get to later in this tutorial).</p>
<p>Let’s see how long this took:</p>
<pre class="r"><code>ShapeTime &lt;- KrigStop - KrigStart
ShapeTime</code></pre>
<pre><code>## Time difference of 3.670155 secs</code></pre>
<p>Running this downscaling process for Saxony using the shapefile took 0.0747352 of the original downscaling time using an extent statement.</p>
<p class="atten">
Using a <code>shapefile</code> rather than an <code>extent</code> statement <strong>speeds up</strong> the <strong>Kriging process</strong>!
</p>
</div>
</div>
<div id="kriging-for-point-data" class="section level2">
<h2>Kriging For Point-Data</h2>
<p class="lookhere">
<code>KrigR</code> also support point-data which is usually used for plot/observation measurements.
</p>
<p>Often times, we only require data for a certain number of geo-referenced locations which may be separated by large areas of no interest to a given analysis. For these analyses, drawing a shapefile around all locations is already a big step up from just using the extent of the area within which the locations fall. That being said, such a shapefile could still cover big areas of which are of no consideration to our analysis. We have this implemented support for point-data input in <code>KrigR</code>.</p>
<p>Let’s first look at the data for this example. Here, we will use hypothetical sightings of Bigfoot:</p>
<pre class="r"><code>Bigfoot.URL &lt;- &quot;https://opendata.arcgis.com/datasets/9947fc49e6c44120b4a1b3133c073dbc_0.csv&quot; # link to the data
Bigfoot.data &lt;- read.csv(Bigfoot.URL) # red the data
Bigfoot_ext &lt;- extent(min(Bigfoot.data$Lon), max(Bigfoot.data$Lon),
                      min(Bigfoot.data$Lat), max(Bigfoot.data$Lat))
BigfootLand &lt;- crop(LandMask , Bigfoot_ext)
bmaps.plot(bbox = Bigfoot_ext, type = &quot;AerialWithLabels&quot;, quiet = TRUE, progress = &quot;none&quot;)
osm.points(x = Bigfoot.data$Lon,
           y = Bigfoot.data$Lat,
           pch=10, cex=0.3, col = &quot;red&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/PointsMap1-1.png" width="1440" /></p>
<p>As we can see, Bigfoot is mostly reported to be found in the west and east of the contiguous US with some occurrences ranging across Canada and Alaska. Quite obviously, there are large areas here, within which we do not require fine-resolution climate data to understand Bigfoot occurrence.</p>
<p>What does this look like with our land mask?</p>
<pre class="r"><code>ggplot() + 
  geom_polygon(data = BigfootLand, aes(x = long, y = lat, group = group), colour = &quot;red&quot;, fill = &quot;lightgrey&quot;) +
  geom_point(data = Bigfoot.data, aes(x = Lon, y = Lat), pch = 3) +
  theme_bw() + labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/PointsMap2-1.png" width="1440" /></p>
<p>We could use the cropped land mask above to download some data. This would already be better than going by extent of the point-data since we bypass sea-areas. However, <code>KrigR</code> can do better. To visualise how this works, we create a smaller subset of the Bigfoot location data here:</p>
<pre class="r"><code>set.seed(42)
Bigfoot_sample &lt;- sample(x = 1:dim(Bigfoot.data)[1], size = 60)
Bigfoot_df &lt;- Bigfoot.data[Bigfoot_sample, ]</code></pre>
<p>So what does this look like on a map?</p>
<pre class="r"><code>Bigfoot_ext &lt;- extent(min(Bigfoot_df$Lon), max(Bigfoot_df$Lon),
                      min(Bigfoot_df$Lat), max(Bigfoot_df$Lat))
BigfootLand &lt;- crop(LandMask , Bigfoot_ext)
ggplot() + 
  geom_polygon(data = BigfootLand, aes(x = long, y = lat, group = group), colour = &quot;red&quot;, fill = &quot;lightgrey&quot;) +
  geom_point(data = Bigfoot_df, aes(x = Lon, y = Lat), pch = 3, cex = 4) +
  theme_bw() + labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/PointsMap3-1.png" width="1440" /></p>
<p>We’ve obtained a nice sample showing distinct patches of Bigfoot occurrences in the west and east parts of the contiguous US. Again, the shapefile we would make from this with the landmask would cover vast areas which we would not be interested in and thus rack up processing time without a payoff. But what if we drew a tiny extent around each of our locations? <code>KrigR</code> can do that for you!</p>
<p>Before we get stuck in with this, we create a directory for our following analysis before we proceed:</p>
<pre class="r"><code>Dir.Points &lt;- file.path(Dir.Data, &quot;Point_Data&quot;)
dir.create(Dir.Points)</code></pre>
<div id="climate-data-2" class="section level3">
<h3>Climate Data</h3>
<p>Now, it is time to obtain climate data for our Bigfoot sightings. To do so within <code>KrigR</code> we make use of three arguments:</p>
<ol style="list-style-type: decimal">
<li><code>Extent</code> - Here, we provide <code>KrigR</code> with a data frame containing <em>Lat</em> and <em>Lon</em> coordinates with columns that are named as such.<br />
</li>
<li><code>Buffer</code> - How big a rectangular (square, to be precise) buffer to draw around each location. This is measured in centesimal degrees.<br />
</li>
<li><code>ID</code> - Column name in our <code>Extent</code>-object containing unique location/observation/plot identifiers.</li>
</ol>
<p>You might already ask yourself? <em>“What if two or more buffers overlap?”</em> Well, these buffers are <strong>fused</strong> automatically to build a single polygon.</p>
<p>Here, we are after a climatology or air temperature spanning the years 1982 - 2012 in a 0.1 degree square buffer around around each of our sampled Bigfoot occurrences. Since downloading this data set takes quite a while, I have implemented a check here to make skip downloading and formatting of the data if it has already been done:</p>
<pre class="r"><code>if (!file.exists(file.path(Dir.Points, &quot;AT_Climatology.nc&quot;))) {
  Points_Raw &lt;- download_ERA(
    Variable = &quot;2m_temperature&quot;,
    DataSet = &quot;era5-land&quot;,
    DateStart = &quot;1982-01-01&quot;,
    DateStop = &quot;2012-12-31&quot;,
    TResolution = &quot;year&quot;,
    TStep = 30,
    Extent = Bigfoot_df, # the point data with Lon and Lat columns
    Buffer = 0.1, # a 0.1 degree buffer should be drawn around each point
    ID = &quot;FID_&quot;, # this is the column which holds point IDs
    API_User = API_User,
    API_Key = API_Key,
    Dir = Dir.Points,
    FileName = &quot;AT_Climatology.nc&quot;
  )
} else {
  Points_Raw &lt;- raster(file.path(Dir.Points, &quot;AT_Climatology.nc&quot;))
}
Plot_Raw(Points_Raw, Shp = BigfootLand, Dates = c(&quot;Climatology&quot;))</code></pre>
<img src="{{< blogdown/postref >}}index.en_files/figure-html/ClimPoints-1.png" width="1440" />
<p class="lookhere">
Setting the <code>Extent</code> argument to be a <code>data.frame</code> object containing <strong>Lat</strong> and <strong>Lon</strong> data, you can obtain climate reanalysis data around locations/points. This can be controlled using the <code>Buffer</code> and <code>ID</code> arguments.
</p>
</div>
<div id="covariates-3" class="section level3">
<h3>Covariates</h3>
<p>Next, we need covariates. We obtain these using the same arguments as we used in our call to <code>download_ERA</code>:</p>
<pre class="r"><code>Covs_ls &lt;- download_DEM(
  Train_ras = Points_Raw,
  Target_res = .02,
  Keep_Temporary = TRUE,
  Shape = Bigfoot_df, # the point data with Lon and Lat columns
  Buffer = 0.1, # a 0.1 degree buffer should be drawn around each point
  ID = &quot;FID_&quot;, # this is the column which holds point IDs
  Dir = Dir.Points
)
Plot_Covs(Covs_ls, Shp = BigfootLand)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/CovPoints-1.png" width="1440" /></p>
</div>
<div id="kriging-2" class="section level3">
<h3>Kriging</h3>
<p>Finally, we are ready to krig our data. This is done the exact same way as in any other approach. However, to be sensible, I add the use of the <code>maxdist</code> argument (passed on to <code>gstat::krige</code>) here. I set it to the same value as the <code>Buffer</code> argument previously so that we perform local Kriging (more on that later) by looking only at data that is no further than what we set our <code>maxdist</code> to:</p>
<pre class="r"><code>KrigStart &lt;- Sys.time() # record when we started
Points_Krig &lt;- krigR(
  Data = Points_Raw,
  Covariates_coarse = Covs_ls[[1]],
  Covariates_fine = Covs_ls[[2]],
  Keep_Temporary = FALSE,
  Cores = 1,
  Dir = Dir.Points,
  FileName = &quot;Points.nc&quot;,
  maxdist = 0.1 # only krig in areas of 0.1 around each location
)
KrigStop &lt;- Sys.time() # record when the function was done
Plot_Krigs(Points_Krig, Shp = BigfootLand, Dates = c(&quot;Climatology&quot;))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/KrigPoints-1.png" width="1440" />
That went by quick! We can’t really see the results clearly here and will look at the in more detail in just a second. Firstly, let’s see how long this took:</p>
<pre class="r"><code>PointsTime &lt;- KrigStop - KrigStart
PointsTime</code></pre>
<pre><code>## Time difference of 10.69015 secs</code></pre>
<p>From experience, Kriging for a region this large instead of just for small regions around locations would easily take upwards of 10 hours! This is a big improvement.</p>
<p>What did we gain by doing this? Why not just obtain the raw reanalysis data and be done with it? For this, we plot our data:</p>
<pre class="r"><code>## DATA EXTRACTION
AirTemp_Krig &lt;- raster::extract(
  x = stack(Points_Krig[-3]),
  y = Bigfoot_df[, c(&quot;Lon&quot;, &quot;Lat&quot;)]
)
AirTemp_Coarse &lt;- raster::extract(
  x = stack(Points_Raw),
  y = Bigfoot_df[, c(&quot;Lon&quot;, &quot;Lat&quot;)]
)
## DATA PREPARATION
ggplot_df &lt;- data.frame(
  Data = c(AirTemp_Coarse, AirTemp_Krig[, 1]),
  Source = rep(c(&quot;Native&quot;, &quot;Kriged&quot;), each = nrow(Bigfoot_df)),
  Difference = c(AirTemp_Coarse - AirTemp_Krig[, 1]),
  Uncertainty = AirTemp_Krig[, 2],
  Index = 1:nrow(Bigfoot_df)
)
## DENSITIES
Densities_gg &lt;- ggplot(data = ggplot_df, aes(x = Data, fill = Source)) +
  geom_density(alpha = 0.42) +
  theme_bw() +
  labs(x = &quot;Density&quot;, y = &quot;Air Temperature&quot;)
## DIFFERENCES
Difference_gg &lt;- ggplot(data = ggplot_df, aes(x = Index, y = Difference)) +
  geom_point(cex = 5, pch = 18) +
  geom_errorbar(aes(ymin = Difference - Uncertainty, ymax = Difference + Uncertainty)) +
  geom_abline(intercept = 0, slope = 0, col = &quot;red&quot;, lwd = 1.5) +
  theme_bw() +
  labs(x = &quot;Location&quot;, y = &quot;Native vs. Kriged Temprature-Difference&quot;)
### FINAL PLOT
plot_grid(plotlist = list(Densities_gg, Difference_gg), nrow = 1, labels = &quot;AUTO&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/PointsZoom-1.png" width="1440" /></p>
<p>Looking at the <em>density distributions</em> we can see a higher peak of intermediate temperature values when compared to the native Era5-Land data. However, that is not a big difference. This is even more evident when looking at the <em>differences between native and kriged data</em>. Many of the data points therein fall close to a difference of 0K. Taking into account the kriging uncertainty, not many fall significantly outside of the 0K range. Thjat being said, there are outliers which might be very important in understanding the physiology of Bigfoot.</p>
<p class="atten">
By obtaining climate reanalysis data around locations/points and subsequently downscaling these, we can obtain <strong>more precise local data</strong>.
</p>
<p>Of course, you can do what we did above in just one call to the <code>KrigR</code> pipeline with the following specification:</p>
<pre class="r"><code>krigR(
  Variable = &quot;2m_temperature&quot;,
  DataSet = &quot;era5-land&quot;,
  Type = &quot;reanalysis&quot;,
  DateStart = &quot;1982-01-01&quot;,
  DateStop = &quot;2012-12-31&quot;,
  TResolution = &quot;year&quot;,
  TStep = 30,
  Extent = Bigfoot_df, # the point data with Lon and Lat columns
  Buffer = 0.1, # a 0.1 degree buffer should be drawn around each point
  ID = &quot;FID_&quot;, # this is the column which holds point IDs
  API_User = API_User,
  API_Key = API_Key,
  Target_res = .02,
  Cores = 1,
  maxdist = 0.1,
  FileName = &quot;Points.nc&quot;,
  Keep_Temporary = FALSE
)</code></pre>
</div>
</div>
<div id="multi-core-kriging" class="section level2">
<h2>Multi-Core Kriging</h2>
<p class="lookhere">
The computational cost of Kriging can be divided up amongst multiple cores using our <code>krigR()</code> function and the <code>Cores</code> argument therein. This enables parallel computation of multi-layer rasters.
</p>
<p>Let’s stick with our shapefile-informed downscaling of air temperature records across Saxony. First, we again obtain our data:</p>
<pre class="r"><code>State_Raw &lt;- download_ERA(
  Variable = &quot;2m_temperature&quot;,
  DataSet = &quot;era5-land&quot;,
  DateStart = &quot;1995-01-02&quot;,
  DateStop = &quot;1995-01-04&quot;,
  TResolution = &quot;day&quot;,
  TStep = 1,
  Extent = State_Shp,
  Dir = Dir.StateShp,
  API_User = API_User,
  API_Key = API_Key
)
Covs_ls &lt;- download_DEM(
  Train_ras = State_Raw,
  Target_res = .02,
  Shape = State_Shp,
  Dir = Dir.StateShp,
  Keep_Temporary = TRUE
)</code></pre>
<p>This time, however, we make use of the <code>Cores</code> argument in the <code>krigR()</code> function to run the downscaling of our three time steps worth of data in paralle:.</p>
<pre class="r"><code>KrigStart &lt;- Sys.time() # record when we started
State_Krig &lt;- krigR(
  Data = State_Raw, # what to krig
  Covariates_coarse = Covs_ls[[1]], # covariates at training resolution
  Covariates_fine = Covs_ls[[2]], # covariates at target resolution
  Keep_Temporary = FALSE, # delete temporary krigs of layers
  Cores = 3, # run this on 3 core
  FileName = &quot;State_Cores.nc&quot;, # save the finished file as this
  Dir = Dir.StateShp # where to save the output
)
KrigStop &lt;- Sys.time() # record when the function was done
Plot_Krigs(State_Krig, Shp = State_Shp, Dates = c(&quot;02-01-1995&quot;, &quot;03-01-1995&quot;, &quot;04-01-1995&quot;))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/KrigCores-1.png" width="1440" /></p>
<p>The results look just like the ones that we obtained without using the shapefile and just one-core processing. Let’s see how long this took:</p>
<pre class="r"><code>CoreTime &lt;- KrigStop - KrigStart
CoreTime</code></pre>
<pre><code>## Time difference of 8.603323 secs</code></pre>
<p>Running this downscaling process for Saxony using the shapefile took 2.3441307 of the original downscaling time using an extent statement (the effects multi-core Kriging really kick in when looking at rasters with many bands because the initial opening of clusters for parallel processing takes some time by itself.).</p>
<p class="atten">
Using the <code>Cores</code> argument with a value of n (with n &gt; 1) <strong>speeds up</strong> the <strong>Kriging process</strong> of multi-layer rasters by an order of n!
</p>
</div>
<div id="weighted-local-kriging" class="section level2">
<h2>Weighted Local Kriging</h2>
<p class="lookhere">
By default Kriging of the <code>krigR()</code> function uses all cells in a spatial product to downscale individual cells of rasters. The <code>nmax</code> argument can circumvent this.
</p>
<p>Let’s build further on our above example by adding the <code>nmax</code> argument (passed on to <code>gstat::krige()</code>) to our <code>krigR()</code> function call. This argument controls how many of the closest cells the Kriging algorithm should consider in the downscaling of individual coarse, training cells.</p>
<pre class="r"><code>State_Krig &lt;- krigR(
  Data = State_Raw, # what to krig
  Covariates_coarse = Covs_ls[[1]], # covariates at training resolution
  Covariates_fine = Covs_ls[[2]], # covariates at target resolution
  Keep_Temporary = FALSE, # delete temporary krigs of layers
  Cores = 3, # only run this on 1 core
  FileName = &quot;State_Local.nc&quot;, # save the finished file as this
  Dir = Dir.StateShp, # where to save the output
  nmax = 15 # how many nearest neighbours to consider in Kriging
)
Plot_Krigs(State_Krig, Shp = State_Shp, Dates = c(&quot;02-01-1995&quot;, &quot;03-01-1995&quot;, &quot;04-01-1995&quot;))</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/KrigNmax-1.png" width="1440" /></p>
<p>The air temperature prediction/downscaling results look just like the ones that we obtained above. However, we seriously improved our localised understanding of Kriging uncertainties (i.e. we see much more localised patterns of Kriging standard error). In this case for Saxony, our uncertainties seem to be highest for areas where the landscape is dominated by large, abrupt changes in elevation (e.g. around the Fichtelberg along the southern border) and water-dominated areas such as streams and lakes (e.g. the lakes around Leipzig in the North of Saxony).</p>
<p class="atten">
Using the <code>nmax</code> argument helps to identify highly localised patterns in the Kriging uncertainty as well as predictions!
</p>
<p>We are working on an automatic feature for the identification of an appropriate number of <code>nmax</code> straight from the data itself.</p>
</div>
<div id="aggregation-of-temporal-resolutions" class="section level2">
<h2>Aggregation of Temporal Resolutions</h2>
<p class="lookhere">
The <code>KrigR</code> package is capable of some neat pre-processing of raw climate data. - both spatially and temporally.
</p>
<p>The functions used for downloading reanalysis data with the <code>KrigR</code> package (<code>download_ERA()</code> and <code>download_UERRA()</code>) accept the following arguments which you can use to control the temporal resolution of your climate data:<br />
- <code>TResolution</code> controls the time-line that <code>TStep</code> indexes. You can specify anything from the following: <code>'hour'</code>, <code>'day'</code>, <code>'month'</code>, or <code>'year'</code>. The default is <code>'month'</code>.<br />
- <code>TStep</code> controls how many time-steps to aggregate into one layer of data each. Aggregation is done via taking the mean per cell in each raster comprising time steps that go into the final, aggregated time-step. The default is <code>1</code>.<br />
- <code>FUN</code> controls which values to calculate for the temporal aggregates, e.g.: <code>'min'</code>, <code>'max'</code>, or <code>'mean'</code> (default).</p>
<p class="atten">
Specifying <code>FUN</code> only does something when a <code>Tstep</code> &gt; 1 is specified - otherwise, there is no temporal aggregation to be done.
</p>
<p><code>KrigR</code> automatically identifies which data set to download from given your temporal aggregation specification. As soon as <code>TResolution</code> is set to <code>'month'</code> or <code>'year'</code>, the package automatically downloads monthly mean data from the CDS. We do this to make the temporal aggregtation calculation more light-weight on your computing units and to make downloads less heavy.</p>
<p class="lookhere">
If you want to obtain the most extreme minima/maxima for a given time-period, you need to specify a <code>TResolution</code> of <code>'hour'</code> or <code>'day'</code> so that temporal aggregation is carried out on hourly data.
</p>
<p>Let’s run through a few examples to make clear how desired temporal resolution of data can be achieved using the <code>KrigR</code> package:</p>
<table>
<colgroup>
<col width="30%" />
<col width="37%" />
<col width="31%" />
</colgroup>
<thead>
<tr class="header">
<th>What we want</th>
<th><code>TResolution</code></th>
<th><code>TStep</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hourly intervals</td>
<td><code>'hour'</code></td>
<td><code>1</code> / don’t specify</td>
</tr>
<tr class="even">
<td>6-hour intervals</td>
<td><code>'hour'</code></td>
<td><code>6</code></td>
</tr>
<tr class="odd">
<td>Half-day intervals</td>
<td><code>'hour'</code></td>
<td><code>12</code></td>
</tr>
<tr class="even">
<td>Daily intervals</td>
<td><code>'day'</code></td>
<td><code>1</code> / don’t specify</td>
</tr>
<tr class="odd">
<td>3-day intervals</td>
<td><code>'day'</code></td>
<td><code>3</code></td>
</tr>
<tr class="even">
<td>Weekly intervals</td>
<td><code>'day'</code></td>
<td><code>7</code></td>
</tr>
<tr class="odd">
<td>Monthly aggregates</td>
<td><code>'month'</code> / don’t specify</td>
<td><code>1</code> / don’t specify</td>
</tr>
<tr class="even">
<td>4-month intervals</td>
<td><code>'month'</code> / don’t specify</td>
<td><code>4</code></td>
</tr>
<tr class="odd">
<td>Annual intervals</td>
<td><code>'year'</code></td>
<td><code>1</code> / don’t specify</td>
</tr>
<tr class="even">
<td>10-year intervals</td>
<td><code>'year'</code></td>
<td><code>10</code></td>
</tr>
</tbody>
</table>
<p class="atten">
Specifying <code>TResolution</code> of <code>'month'</code> will result in the download of full month aggregates for every month included in your time series.
</p>
<p>For example, <code>DateStart = "2000-01-20"</code>, <code>DateStop = "2000-02-20"</code> with <code>TResolution = 'month'</code>, and <code>TStep = 1</code> <strong>does not</strong> result in the mean aggregate for the month between the 20/01/200 and the 20/02/2000, but <strong>does result</strong> in the monthly aggregates for January and February 2000. If you desire the former, you would need to specify <code>DateStart = "2000-01-20"</code>, <code>DateStop = "2000-02-20"</code> with <code>TResolution = 'day'</code>, and <code>TStep = 32</code> (the number of days between the two dates).</p>
<p class="lookhere">
The reanalysis download functions of the <code>KrigR</code> package automatically break down download requests into monthly intervals thus circumventing the danger of running into making a download request that is too big for the CDS.
</p>
<p>For example, <code>DateStart = "2000-01-20"</code>, <code>DateStop = "2000-02-20"</code> with <code>TResolution = 'day'</code>, and <code>TStep = 8</code> will lead to two download requests to the CDS: (1) hourly data in the range 20/01/2000 00:00 to 31/01/2000 23:00, and (2) hourly data in the range 01/02/2000 00:00 to 20/02/2000 23:00. These data sets are subsequently fused in <code>R</code>, aggregated to daily aggregates, and finally, aggregated to four big aggregates.</p>
<p>This gives you a lot of flexibility, but always keep in mind that third-party data sets might not account for leap-years so make sure the dates of third-party data (should you chose to use some) lines up with the ones as specified by your calls to the functions of the <code>KrigR</code> package.</p>
<p class="atten">
Use the <code>TResolution</code>, and <code>TStep</code> arguments in the <code>download_ERA()</code>, and <code>download_UERRA()</code> functions of the <code>KrigR</code> package to adjust the temporal resolution of your climate data when downloading reanalysis data with our package.
</p>
</div>
<div id="kriging-to-match-already-available-data" class="section level2">
<h2>Kriging to Match Already Available Data</h2>
<p>We expect that you won’t want to downscale to specific resolutions most of the time, but rather, match an already existing spatial data set in terms of spatial resolution and extent. Again, the <code>KrigR</code> package got you covered!</p>
<p class="lookhere">
Usually, you probably want to krig to match a certain pre-existing data set rather than a certain resolution.
</p>
<p>Here, we illustrate this with an NDVI-based example. The NDVI is a satellite-derived vegetation index which tells us how green the Earth is. It comes in bi-weekly intervals and at a spatial resolution of <code>.08333</code> (roughly 9km). Here, we download all NDVI data for the year 2000 and then create the annual mean. This time, we do so for the state of California because of its size and topographical variety.</p>
<pre class="r"><code>Position &lt;- which(StateMask$name_en == &quot;California&quot;) # find our state
State_Shp &lt;- StateMask[Position, ] # extract shapefile
if (!file.exists(file.path(Dir.Data, &quot;ReferenceRaster.nc&quot;))) { # if reference raster doesn&#39;t already exist
  gimms_files &lt;- downloadGimms(
    x = as.Date(&quot;2000-01-01&quot;), # download from January 2000
    y = as.Date(&quot;2000-12-31&quot;), # download to December 2000
    dsn = Dir.Data, # save downloads in data folder
    quiet = FALSE
  ) # show download progress
  Reference_ras &lt;- rasterizeGimms(x = gimms_files, remove_header = TRUE) # rasterize the data
  Negatives &lt;- which(values(Reference_ras) &lt; 0) # identify all negative values
  values(Reference_ras)[Negatives] &lt;- 0 # set threshold for barren land (NDVI&lt;0)
  Reference_ras &lt;- calc(Reference_ras, fun = mean, na.rm = TRUE) # annual mean
  Reference_ras &lt;- crop(Reference_ras, State_Shp) # crop to fit shape
  Reference_ras &lt;- mask(Reference_ras, State_Shp) # mask by shape
  writeRaster(x = Reference_ras, filename = file.path(Dir.Data, &quot;ReferenceRaster&quot;), format = &quot;CDF&quot;) # write raster to data directory
  unlink(gimms_files, recursive = TRUE) # delete raw GIMMs data
  rm(list = c(&quot;Negatives&quot;, &quot;gimms_files&quot;)) # delete from environment
} else { # if reference raster already exists
  Reference_ras &lt;- raster(file.path(Dir.Data, &quot;ReferenceRaster.nc&quot;)) # GIMMs NDVI data as baseline raster
}</code></pre>
<p>So what does this raster look like?</p>
<pre class="r"><code>Reference_ras</code></pre>
<pre><code>## class      : RasterLayer 
## dimensions : 114, 124, 14136  (nrow, ncol, ncell)
## resolution : 0.08333333, 0.08333333  (x, y)
## extent     : -124.4167, -114.0833, 32.5, 42  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : D:/Documents/Website/content/post/krigr-mats/28-01-2021-WorkShop/Data/ReferenceRaster.nc 
## names      : layer 
## values     : 0.007266667, 0.8722875  (min, max)
## zvar       : layer</code></pre>
<p>As stated above, we want to match this with our output.</p>
<p>So, let’s create our directory for this as we did before:</p>
<pre class="r"><code>Dir.NDVI &lt;- file.path(Dir.Data, &quot;NDVI_Matching&quot;)
dir.create(Dir.NDVI)</code></pre>
<p>We could do this whole analysis in our three steps as outlined above, but why bother when the pipeline described above gets the job done just as well?</p>
<p class="atten">
Matching Kriging outputs with a pre-existing data set is as easy as plugging the pre-existing raster into the <code>Target_res</code> argument of the <code>krigR()</code> or the <code>download_DEM()</code> function.
</p>
<p>This time we want to downscale from ERA5 resolution (roughly 30km) because the ERA5-Land data already matches the NDVI resolution (roughly 9km). Here’s how we do this:</p>
<pre class="r"><code>NDVI_Krig &lt;- krigR(
  Variable = &quot;2m_temperature&quot;,
  Type = &quot;reanalysis&quot;,
  DataSet = &quot;era5&quot;,
  DateStart = &quot;2000-01-01&quot;,
  DateStop = &quot;2000-12-31&quot;,
  TResolution = &quot;year&quot;,
  TStep = 1,
  Extent = State_Shp,
  API_User = API_User,
  API_Key = API_Key,
  Target_res = Reference_ras,
  Cores = 1,
  FileName = &quot;AirTemp_NDVI.nc&quot;,
  nmax = 80, # we are still working on an automatic optimisation of this. Here, let&#39;s try a bigger number
  Dir = Dir.NDVI
)</code></pre>
<p>So? Did we match the pre-existing data?</p>
<pre class="r"><code>NDVI_Krig[[1]]</code></pre>
<pre><code>## class      : RasterBrick 
## dimensions : 114, 124, 14136, 1  (nrow, ncol, ncell, nlayers)
## resolution : 0.08333333, 0.08333333  (x, y)
## extent     : -124.4167, -114.0833, 32.5, 42  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : var1.pred 
## min values :  271.4974 
## max values :   299.116</code></pre>
<p>We nailed this!</p>
<p>Let’s take one final look at our (A) raw ERA5 data, (B) NDVI data, (C) Kriged ERA5 data, and (D) standard error of our Kriging output:</p>
<pre class="r"><code>### ERA-Plot
ERA_df &lt;- as.data.frame(raster(file.path(Dir.NDVI, &quot;2m_temperature_2000-01-01_2000-12-31_year.nc&quot;)), xy = TRUE) # turn raster into dataframe
colnames(ERA_df)[c(-1, -2)] &lt;- &quot;Air Temperature 2000 (ERA5)&quot;
ERA_df &lt;- gather(data = ERA_df, key = Values, value = &quot;value&quot;, colnames(ERA_df)[c(-1, -2)]) #  make ggplot-ready
Raw_plot &lt;- ggplot() + # create a plot
  geom_raster(data = ERA_df, aes(x = x, y = y, fill = value)) + # plot the raw data
  facet_wrap(~Values) + # split raster layers up
  theme_bw() +
  labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;) + # make plot more readable
  scale_fill_gradientn(name = &quot;Air Temperature [K]&quot;, colours = inferno(100)) + # add colour and legend
  geom_polygon(data = State_Shp, aes(x = long, y = lat, group = group), colour = &quot;black&quot;, fill = &quot;NA&quot;) # add shape
### NDVI-Plot
NDVI_df &lt;- as.data.frame(Reference_ras, xy = TRUE) # turn raster into dataframe
colnames(NDVI_df)[c(-1, -2)] &lt;- &quot;NDVI 2000&quot;
NDVI_df &lt;- gather(data = NDVI_df, key = Values, value = &quot;value&quot;, colnames(NDVI_df)[c(-1, -2)]) #  make ggplot-ready
NDVI_plot &lt;- ggplot() + # create a plot
  geom_raster(data = NDVI_df, aes(x = x, y = y, fill = value)) + # plot the raw data
  facet_wrap(~Values) + # split raster layers up
  theme_bw() +
  labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;) + # make plot more readable
  scale_fill_gradientn(name = &quot;NDVI&quot;, colours = rev(terrain.colors(100))) + # add colour and legend
  geom_polygon(data = State_Shp, aes(x = long, y = lat, group = group), colour = &quot;black&quot;, fill = &quot;NA&quot;) # add shape
### KRIGED-Plots
Dates &lt;- c(&quot;Kriged Air Temperature 2000 (NDVI Resolution)&quot;)
Type_vec &lt;- c(&quot;Prediction&quot;, &quot;Standard Error&quot;) # these are the output types of krigR
Colours_ls &lt;- list(inferno(100), rev(viridis(100))) # we want separate colours for the types
Plots_ls &lt;- as.list(NA, NA) # this list will be filled with the output plots
for (Plot in 1:2) { # loop over both output types
  Krig_df &lt;- as.data.frame(NDVI_Krig[[Plot]], xy = TRUE) # turn raster into dataframe
  colnames(Krig_df)[c(-1, -2)] &lt;- paste(Type_vec[Plot], Dates) # set colnames
  Krig_df &lt;- gather(data = Krig_df, key = Values, value = &quot;value&quot;, colnames(Krig_df)[c(-1, -2)]) # make ggplot-ready
  Plots_ls[[Plot]] &lt;- ggplot() + # create plot
    geom_raster(data = Krig_df, aes(x = x, y = y, fill = value)) + # plot the kriged data
    facet_wrap(~Values) + # split raster layers up
    theme_bw() +
    labs(x = &quot;Longitude&quot;, y = &quot;Latitude&quot;) + # make plot more readable
    scale_fill_gradientn(name = &quot;Air Temperature [K]&quot;, colours = Colours_ls[[Plot]]) + # add colour and legend
    theme(plot.margin = unit(c(0, 0, 0, 0), &quot;cm&quot;)) + # reduce margins (for fusing of plots)
    geom_polygon(data = State_Shp, aes(x = long, y = lat, group = group), colour = &quot;black&quot;, fill = &quot;NA&quot;) # add shape
} # end of type-loop
### FINAL PLOT
plot_grid(plotlist = list(Raw_plot, NDVI_plot, Plots_ls[[1]], Plots_ls[[2]]), nrow = 2, labels = &quot;AUTO&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/unnamed-chunk-4-1.png" width="1440" /></p>
</div>
<div id="the-call-list" class="section level2">
<h2>The Call List</h2>
<p>So far, we have only ever looked at the first two elements in the list returned by <code>krigR()</code>. A quick look at the help file, the code, or this guide reveals that there is a third list element - the <em>call list</em>. When coding this feature into <code>krigR()</code> we intended for this to be a neat, clean, storage-friendly way of keeping track of how the spatial product was created. It does so without storing additional spatial products. Let’s have a look at it:</p>
<pre class="r"><code>NDVI_Krig[[3]]</code></pre>
<pre><code>## $Data
## $Data$Class
## [1] &quot;RasterLayer&quot;
## attr(,&quot;package&quot;)
## [1] &quot;raster&quot;
## 
## $Data$Dimensions
## $Data$Dimensions$nrow
## [1] 20
## 
## $Data$Dimensions$ncol
## [1] 23
## 
## $Data$Dimensions$ncell
## [1] 460
## 
## 
## $Data$Extent
## class      : Extent 
## xmin       : -125.16 
## xmax       : -113.659 
## ymin       : 32.282 
## ymax       : 42.282 
## 
## $Data$CRS
## CRS arguments: +proj=longlat +datum=WGS84 +no_defs 
## 
## $Data$layers
## [1] &quot;index_1&quot;
## 
## 
## $Covariates_coarse
## $Covariates_coarse$Class
## [1] &quot;RasterLayer&quot;
## attr(,&quot;package&quot;)
## [1] &quot;raster&quot;
## 
## $Covariates_coarse$Dimensions
## $Covariates_coarse$Dimensions$nrow
## [1] 20
## 
## $Covariates_coarse$Dimensions$ncol
## [1] 23
## 
## $Covariates_coarse$Dimensions$ncell
## [1] 460
## 
## 
## $Covariates_coarse$Extent
## class      : Extent 
## xmin       : -125.16 
## xmax       : -113.659 
## ymin       : 32.282 
## ymax       : 42.282 
## 
## $Covariates_coarse$CRS
## CRS arguments: +proj=longlat +datum=WGS84 +no_defs 
## 
## $Covariates_coarse$layers
## [1] &quot;DEM&quot;
## 
## 
## $Covariates_fine
## $Covariates_fine$Class
## [1] &quot;RasterLayer&quot;
## attr(,&quot;package&quot;)
## [1] &quot;raster&quot;
## 
## $Covariates_fine$Dimensions
## $Covariates_fine$Dimensions$nrow
## [1] 114
## 
## $Covariates_fine$Dimensions$ncol
## [1] 124
## 
## $Covariates_fine$Dimensions$ncell
## [1] 14136
## 
## 
## $Covariates_fine$Extent
## class      : Extent 
## xmin       : -124.4167 
## xmax       : -114.0833 
## ymin       : 32.5 
## ymax       : 42 
## 
## $Covariates_fine$CRS
## CRS arguments: +proj=longlat +datum=WGS84 +no_defs 
## 
## $Covariates_fine$layers
## [1] &quot;DEM&quot;
## 
## 
## $KrigingEquation
## ERA ~ DEM
## &lt;environment: 0x000000003231f400&gt;
## 
## $Cores
## [1] 1
## 
## $FileName
## [1] &quot;AirTemp_NDVI.nc&quot;
## 
## $Keep_Temporary
## [1] TRUE
## 
## $nmax
## [1] 80
## 
## $Data_Retrieval
## $Data_Retrieval$Variable
## [1] &quot;2m_temperature&quot;
## 
## $Data_Retrieval$Type
## [1] &quot;reanalysis&quot;
## 
## $Data_Retrieval$PrecipFix
## [1] FALSE
## 
## $Data_Retrieval$DataSet
## [1] &quot;era5&quot;
## 
## $Data_Retrieval$DateStart
## [1] &quot;2000-01-01&quot;
## 
## $Data_Retrieval$DateStop
## [1] &quot;2000-12-31&quot;
## 
## $Data_Retrieval$TResolution
## [1] &quot;year&quot;
## 
## $Data_Retrieval$TStep
## [1] 1
## 
## $Data_Retrieval$Extent
## class       : SpatialPolygonsDataFrame 
## features    : 1 
## extent      : -124.4092, -114.1191, 32.53167, 41.99954  (xmin, xmax, ymin, ymax)
## crs         : +proj=longlat +datum=WGS84 +no_defs 
## variables   : 83
## names       :         featurecla, scalerank, adm1_code, diss_me, iso_3166_2,                               wikipedia, iso_a2, adm0_sr,       name,  name_alt, name_local,  type, type_en, code_local, code_hasc, ... 
## value       : Admin-1 scale rank,         2,  USA-3521,    3521,      US-CA, http://en.wikipedia.org/wiki/California,     US,       8, California, CA|Calif.,         NA, State,   State,       US06,     US.CA, ...</code></pre>
<p>This lengthy list should contain all information you need to trace how you created a certain data set using <code>krigR()</code>. If you feel like anything is missing in this list, please contact us.</p>
<!-- ## Further Downscaling Recommendations -->
<!-- **covariate-variable pairing table here** -->
</div>
</div>
<div id="using-third-party-data" class="section level1">
<h1>Using Third-Party Data</h1>
<p>Our <code>krigR()</code> function is designed to work with non-ERA climate data as well as non-GMTED2010 covariate data. To krig your own spatial products using different covariate data than the GMTED2010 DEM we use as a default, you need to step into the three-step workflow.</p>
<p class="atten">
<strong>ATTENTION:</strong> Kriging only works on <strong>square-cell spatial products</strong>!
</p>
<p><code>krigR()</code> supports any combination of ERA-family reanalysis, GMTED2010, third-party climate data, and third-party covariate data. Here, we just demonstrate the use of other covariates than the GMTED2010 used by <code>KrigR</code> by default.</p>
<p>For this example, let’s go back to Saxony:</p>
<pre class="r"><code>Position &lt;- which(StateMask$name_en == &quot;Saxony&quot;) # find Saxony
State_Shp &lt;- StateMask[Position, ]</code></pre>
<p>Now, let’s download some covariate data:<br />
- <code>TKSat</code> - thermal conductivity of saturated soil<br />
- <code>TKDry</code> - thermal conductivity of dry soil</p>
<pre class="r"><code>Dir.TP &lt;- file.path(Dir.Data, &quot;Third-Party_Data&quot;)
dir.create(Dir.TP)
#### Thermal Conductivity of saturated soil
if (!file.exists(file.path(Dir.TP, &quot;TKSat.zip&quot;))) { # if not downloaded yet
  download.file(&quot;http://globalchange.bnu.edu.cn/download/data/worldptf/tksat.zip&quot;,
    destfile = file.path(Dir.TP, &quot;TKSat.zip&quot;)
  ) # download cultural vector
  unzip(file.path(Dir.TP, &quot;TKSat.zip&quot;), exdir = Dir.TP) # unzip data
}
TKSat_ras &lt;- raster(file.path(Dir.TP, &quot;tksatu_l1.nc&quot;))

#### Thermal Conductivity of dry soil
if (!file.exists(file.path(Dir.TP, &quot;TKDry.zip&quot;))) { # if not downloaded yet
  download.file(&quot;http://globalchange.bnu.edu.cn/download/data/worldptf/tkdry.zip&quot;,
    destfile = file.path(Dir.TP, &quot;TKdry.zip&quot;)
  ) # download cultural vector
  unzip(file.path(Dir.TP, &quot;TKdry.zip&quot;), exdir = Dir.TP) # unzip data
}
TKDry_ras &lt;- raster(file.path(Dir.TP, &quot;tkdry_l1.nc&quot;))</code></pre>
<div id="climate-data-3" class="section level2">
<h2>Climate Data</h2>
<p>This time, let’s mix it up a bit and look at soil temperature in the uppermost depth layer that ERA5(-Land) recognizes (0-7cm):</p>
<pre class="r"><code>State_Raw &lt;- download_ERA(
  Variable = &quot;soil_temperature_level_1&quot;,
  DataSet = &quot;era5-land&quot;,
  DateStart = &quot;1995-01-02&quot;,
  DateStop = &quot;1995-01-04&quot;,
  TResolution = &quot;day&quot;,
  TStep = 1,
  Extent = State_Shp,
  Dir = Dir.TP,
  API_User = API_User,
  API_Key = API_Key
)
Plot_Raw(State_Raw, Shp = State_Shp, Dates = c(&quot;02-01-1995&quot;, &quot;03-01-1995&quot;, &quot;04-01-1995&quot;), Legend = &quot;Soil Temperature (0-7cm) [K]&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/unnamed-chunk-9-1.png" width="1440" /></p>
</div>
<div id="covariates-4" class="section level2">
<h2>Covariates</h2>
<p>As far as covariate data is concerned, we downloaded and loaded into <code>R</code> global data sets which now limit to Saxony:</p>
<pre class="r"><code>## TKSat
TKSat_ras &lt;- crop(TKSat_ras, extent(State_Raw)) # crop to the right extent of our data we want to krig
Shape_ras &lt;- rasterize(State_Shp, TKSat_ras, getCover = TRUE) # identify which cells are covered by the shape
Shape_ras[Shape_ras == 0] &lt;- NA # set all cells which the shape doesn&#39;t touch to NA
TKSat_ras &lt;- mask(TKSat_ras, Shape_ras) # mask for the shape of the state
## TKDry
TKDry_ras &lt;- crop(TKDry_ras, extent(State_Raw)) # crop to the right extent of our data we want to krig
Shape_ras &lt;- rasterize(State_Shp, TKDry_ras, getCover = TRUE) # identify which cells are covered by the shape
Shape_ras[Shape_ras == 0] &lt;- NA # set all cells which the shape doesn&#39;t touch to NA
TKDry_ras &lt;- mask(TKDry_ras, Shape_ras) # mask for the shape of the state</code></pre>
<p>Personally, I am not content with just looking at thermal conductivity of dry and wet soil in predicting soil temperatures. Other covariates that come to mind are elevation and air temperature (which we can easily provide at target resolution through Kriging it reliably with elevation). Here, we just use some elevation data. Also, let’s push the boundaries and downscale all the way to a 0.01. resolution:</p>
<pre class="r"><code>Covs_ls &lt;- download_DEM(
  Train_ras = State_Raw,
  Target_res = .01,
  Shape = State_Shp,
  Dir = Dir.StateShp,
  Keep_Temporary = TRUE
)</code></pre>
<p>Now we combine these into a list containing to stacks of rasters and plot our third-party covariates:</p>
<pre class="r"><code># resample fine-resolution covariate data to match coarse input data
Coarsecovs &lt;- stack(resample(x = TKSat_ras, y = State_Raw), resample(x = TKDry_ras, y = State_Raw), Covs_ls[[1]])
names(Coarsecovs) &lt;- c(&quot;TKWet&quot;, &quot;TKDry&quot;, &quot;DEM&quot;) # setting some proper names
# High-resolution to which we downscale
Finecovs &lt;- stack(TKSat_ras, TKDry_ras, Covs_ls[[2]])
names(Finecovs) &lt;- c(&quot;TKWet&quot;, &quot;TKDry&quot;, &quot;DEM&quot;) # setting some proper names
# combine data into covariate list
Covs_ls &lt;- list(Coarsecovs, Finecovs)
Plot_Covs(Covs_ls, State_Shp)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/unnamed-chunk-12-1.png" width="1440" /></p>
</div>
<div id="kriging-3" class="section level2">
<h2>Kriging</h2>
<p>Finally, we can krig our soil temperature data using the thermal conductivity of the soil. For this, we need to specify a new <code>KrigingEquation</code>. If we don’t, <code>krigR()</code> will notify us that it our default formula cannot be executed and will attempt to build a formula from the data it can find (this auto-generated formula would be the same as the one we specify here - an additive combination of all covariates found both at coarse and fine resolutions). Of course, this formula can also be specified to reflect interactive effects.</p>
<pre class="r"><code>State_Krig &lt;- krigR(
  Data = State_Raw, # what to krig
  Covariates_coarse = Covs_ls[[1]], # covariates at training resolution
  Covariates_fine = Covs_ls[[2]], # covariates at target resolution
  Keep_Temporary = FALSE, # delete temporary krigs of layers
  Cores = 3, # run this on 3 cores
  KrigingEquation = &quot;ERA ~ DEM + TKDry + TKWet&quot;, # this time, we need to specify a new formula. Try and see what happens if you forget to do this.
  FileName = &quot;State_TP.nc&quot;, # save the finished file as this
  Dir = Dir.TP, # where to save the output
  nmax = 15 # how many nearest neighbours to consider in Kriging
)</code></pre>
<pre><code>## Warning in KrigR:::check_Krig(Data = Data, CovariatesCoarse = Covariates_coarse, : It is not recommended to use kriging for statistical downscaling of more than one order of magnitude. You are
## currently attempting this. Kriging will proceed.</code></pre>
<pre class="r"><code>Plot_Krigs(State_Krig, Shp = State_Shp, Dates = c(&quot;02-01-1995&quot;, &quot;03-01-1995&quot;, &quot;04-01-1995&quot;), Legend = &quot;Soil Temperature (0-7cm) [K]&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/unnamed-chunk-13-1.png" width="1440" />
Setting aside the output of the Kriging itself, you find a warning message produced by <code>krigR()</code> - since we specified a resolution of 0.01 as our target and our raw data (both third-party and GMTED2010) comes at a native resolution of 0.0083, we cannot aggregate to 0.01 and are stuck with 0.0083. <code>krigR()</code> warns us that this means we krig below the threshold of 0.09 which could be argued to be sensible bny rule of thumb as our lowest resolution we might go to, but proceeds with the Kriging.</p>
<p class="atten">
You can use the <code>KrigingEquation</code> argument in <code>krigR()</code> to specify the use of third-party covariates and/or data to be kriged. You can specify additive as well as interaction effects.
</p>
</div>
</div>
<div id="session-info" class="section level1">
<h1>Session Info</h1>
<pre class="r"><code>sessionInfo()</code></pre>
<pre><code>## R version 4.0.2 (2020-06-22)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 18363)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
## [5] LC_TIME=English_United Kingdom.1252    
## 
## attached base packages:
## [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] gimms_1.1.3       rosm_0.2.5        cowplot_1.1.0     viridis_0.5.1     viridisLite_0.3.0 ggplot2_3.3.2     tidyr_1.1.2       KrigR_0.1.0       httr_1.4.2        stars_0.4-3      
## [11] abind_1.4-5       fasterize_1.0.3   sf_0.9-6          lubridate_1.7.9   automap_1.0-14    doParallel_1.0.15 iterators_1.0.12  foreach_1.5.0     rgdal_1.5-18      raster_3.3-13    
## [21] sp_1.4-4          stringr_1.4.0     keyring_1.1.0     ecmwfr_1.3.0      ncdf4_1.17       
## 
## loaded via a namespace (and not attached):
##  [1] xts_0.12.1         R.cache_0.14.0     tools_4.0.2        backports_1.1.10   R6_2.5.0           KernSmooth_2.23-17 zyp_0.10-1.1       rgeos_0.5-5        DBI_1.1.0          colorspace_1.4-1  
## [11] withr_2.3.0        tidyselect_1.1.0   gridExtra_2.3      curl_4.3           compiler_4.0.2     gstat_2.0-6        labeling_0.3       bookdown_0.21      scales_1.1.1       classInt_0.4-3    
## [21] digest_0.6.27      rmarkdown_2.6      R.utils_2.10.1     jpeg_0.1-8.1       pkgconfig_2.0.3    htmltools_0.5.0    styler_1.3.2       rlang_0.4.10       FNN_1.1.3          generics_0.0.2    
## [31] farver_2.0.3       zoo_1.8-8          jsonlite_1.7.2     dplyr_1.0.2        R.oo_1.24.0        magrittr_2.0.1     Rcpp_1.0.5         munsell_0.5.0      lifecycle_0.2.0    R.methodsS3_1.8.1 
## [41] stringi_1.5.3      yaml_2.2.1         plyr_1.8.6         grid_4.0.2         crayon_1.3.4       lattice_0.20-41    knitr_1.30         pillar_1.4.6       boot_1.3-25        rjson_0.2.20      
## [51] spacetime_1.2-3    codetools_0.2-16   glue_1.4.2         evaluate_0.14      blogdown_1.0.2     vctrs_0.3.4        png_0.1-7          gtable_0.3.0       purrr_0.3.4        rematch2_2.1.2    
## [61] reshape_0.8.8      assertthat_0.2.1   xfun_0.20          lwgeom_0.2-5       e1071_1.7-3        class_7.3-17       Kendall_2.2        tibble_3.0.3       intervals_0.15.2   memoise_1.1.0     
## [71] units_0.6-7        ellipsis_0.3.1</code></pre>
</div>
